/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\low_poly_city_pack.glb 
Author: Igor Tretyakov (https://sketchfab.com/vdv77)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-city-pack-7f671f35e9ad4149b83451a3a92a6e2e
Title: low poly city pack
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Camping(props) {
  const { nodes, materials } = useGLTF('/models/low_poly_city_pack.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.001}>
        <group position={[-450.464, 368.523, 2623.864]}>
          <mesh geometry={nodes['������������_������_1_1__13'].geometry} material={materials['1_1__13']} />
          <mesh geometry={nodes['������������_������_1_1_����������������_5'].geometry} material={materials.material_15} />
          <mesh geometry={nodes['������������_������_1_1_����������������2_6'].geometry} material={materials.material_16} />
          <mesh geometry={nodes['������������_������_1_1_����������������11_13'].geometry} material={materials.material_3} />
          <mesh geometry={nodes['������������_������_1_1_����������������5_1'].geometry} material={materials.material_4} />
          <mesh geometry={nodes['������������_������_1_1_����������������27_13'].geometry} material={materials.material_5} />
          <mesh geometry={nodes['������������_������_1_1_����������������19_13'].geometry} material={materials.material_6} />
          <mesh geometry={nodes['������������_������_1_1_����������������6_13'].geometry} material={materials.material_7} />
          <mesh geometry={nodes['������������_������_1_1_����������������12_13'].geometry} material={materials.material_8} />
          <mesh geometry={nodes['������������_������_1_1_����������������17_13'].geometry} material={materials.material_9} />
          <mesh geometry={nodes['������������_������_1_1_����������������10_13'].geometry} material={materials.material_11} />
          <mesh geometry={nodes['������������_������_1_1_����������������3_2'].geometry} material={materials.material_12} />
          <mesh geometry={nodes['������������_������_1_1_����������������1_7'].geometry} material={materials.material_17} />
          <mesh geometry={nodes['������������_������_1_1_����������������26_8'].geometry} material={materials.material_18} />
          <mesh geometry={nodes['������������_������_1_1_����������������7_13'].geometry} material={materials.material_19} />
          <mesh geometry={nodes['������������_������_1_1_����������������8_13'].geometry} material={materials.material_20} />
          <mesh geometry={nodes['������������_������_1_1_����������������11_13_1'].geometry} material={materials['.11_0']} />
          <mesh geometry={nodes['������������_������_1_1_����������������6_13_1'].geometry} material={materials['.6_0']} />
          <mesh geometry={nodes['������������_������_1_1_����������������1_13'].geometry} material={materials['.1_0']} />
          <mesh geometry={nodes['������������_������_1_1_����������������5_13'].geometry} material={materials['.5_0']} />
          <mesh geometry={nodes['������������_������_1_1_����������������3_13'].geometry} material={materials['.3_0']} />
          <mesh geometry={nodes['������������_������_1_1_����������������2_13'].geometry} material={materials['.2_0']} />
          <mesh geometry={nodes['������������_������_1_1_����������������9_13'].geometry} material={materials.material_27} />
          <mesh geometry={nodes['������������_������_1_1_����������������12_13_1'].geometry} material={materials['.12_0']} />
          <mesh geometry={nodes['������������_������_1_1_����������������10_13_1'].geometry} material={materials['.10_0']} />
          <mesh geometry={nodes['������������_������_1_1_����������������13_13'].geometry} material={materials.material_30} />
          <mesh geometry={nodes['������������_������_1_1_����������������14_13'].geometry} material={materials.material_31} />
          <mesh geometry={nodes['������������_������_1_1_����������������9_13_1'].geometry} material={materials['.9_0']} />
          <mesh geometry={nodes['������������_������_1_1_����������������9_13_2'].geometry} material={materials['.9_0']} />
          <mesh geometry={nodes['������������_������_1_1_����������������9_13_3'].geometry} material={materials['.9_0']} />
          <mesh geometry={nodes['������������_������_1_1_����������������9_13_4'].geometry} material={materials['.9_0']} />
          <mesh geometry={nodes['������������_������_1_1_����������������9_13_5'].geometry} material={materials['.9_0']} />
          <mesh geometry={nodes['������������_������_1_1_����������������9_13_6'].geometry} material={materials['.9_0']} />
          <mesh geometry={nodes['������������_������_1_1_����������������9_13_7'].geometry} material={materials['.9_0']} />
          <mesh geometry={nodes['������������_������_1_1_����������������9_13_8'].geometry} material={materials['.9_0']} />
          <mesh geometry={nodes['������������_������_1_1_����������������9_13_9'].geometry} material={materials['.9_0']} />
          <mesh geometry={nodes['������������_������_1_1_����������������9_13_10'].geometry} material={materials['.9_0']} />
          <mesh geometry={nodes['������������_������_1_1_����������������4_13'].geometry} material={materials.material_33} />
          <mesh geometry={nodes['������������_������_1_1_����������������38_13'].geometry} material={materials.material_34} />
          <mesh geometry={nodes['������������_������_1_1_����������������21_13'].geometry} material={materials.material_35} />
          <mesh geometry={nodes['������������_������_1_1_����������������29_13'].geometry} material={materials.material_36} />
          <mesh geometry={nodes['������������_������_1_1_����������������14_13_1'].geometry} material={materials['.14_0']} />
          <mesh geometry={nodes['������������_������_1_1_����������������42_13'].geometry} material={materials.material_38} />
          <mesh geometry={nodes['������������_������_1_1_����������������20_13'].geometry} material={materials.material_39} />
          <mesh geometry={nodes['������������_������_1_1_����������������7_13_1'].geometry} material={materials['.7_0']} />
          <mesh geometry={nodes['������������_������_1_1_����������������8_13_1'].geometry} material={materials['.8_0']} />
          <mesh geometry={nodes['������������_������_1_1_����������������16_13'].geometry} material={materials.material_42} />
          <mesh geometry={nodes['������������_������_1_1_����������������35_13'].geometry} material={materials.material_43} />
          <mesh geometry={nodes['������������_������_1_1_����������������34_13'].geometry} material={materials.material_44} />
          <mesh geometry={nodes['������������_������_1_1_����������������36_13'].geometry} material={materials.material_45} />
          <mesh geometry={nodes['������������_������_1_1_����������������30_13'].geometry} material={materials.material_46} />
          <mesh geometry={nodes['������������_������_1_1_����������������23_13'].geometry} material={materials.material_47} />
          <mesh geometry={nodes['������������_������_1_1_����������������24_13'].geometry} material={materials.material_48} />
          <mesh geometry={nodes['������������_������_1_1_����������������9_13_11'].geometry} material={materials['.9_1']} />
          <mesh geometry={nodes['������������_������_1_1_����������������43_13'].geometry} material={materials.material_50} />
          <mesh geometry={nodes['������������_������_1_1_����������������13_13_1'].geometry} material={materials['.13_0']} />
          <mesh geometry={nodes['������������_������_1_1_����������������13_13_2'].geometry} material={materials['.13_0']} />
          <mesh geometry={nodes['������������_������_1_1_����������������33_13'].geometry} material={materials.material_52} />
          <mesh geometry={nodes['������������_������_1_1_����������������15_13'].geometry} material={materials.material_53} />
          <mesh geometry={nodes['������������_������_1_1_����������������18_13'].geometry} material={materials.material_54} />
          <mesh geometry={nodes['������������_������_1_1_����������������22_13'].geometry} material={materials.material_55} />
          <mesh geometry={nodes['������������_������_1_1_����������������25_13'].geometry} material={materials.material_56} />
          <mesh geometry={nodes['������������_������_1_1_����������������25_13_1'].geometry} material={materials.material_56} />
          <mesh geometry={nodes['������������_������_1_1_����������������31_13'].geometry} material={materials.material_57} />
          <mesh geometry={nodes['������������_������_1_1_����������������1_13_1'].geometry} material={materials['.1_1']} />
          <mesh geometry={nodes['������������_������_1_1_����������������39_13'].geometry} material={materials.material_59} />
          <mesh geometry={nodes['������������_������_1_1_����������������40_13'].geometry} material={materials.material_60} />
          <mesh geometry={nodes['������������_������_1_1_����������������13_13_3'].geometry} material={materials['.13_1']} />
          <mesh geometry={nodes['������������_������_1_1_����������������11_13_2'].geometry} material={materials['.11_1']} />
          <mesh geometry={nodes['������������_������_1_1_����������������10_13_2'].geometry} material={materials['.10_1']} />
          <mesh geometry={nodes['������������_������_1_1_����������������5_13_1'].geometry} material={materials['.5_1']} />
          <mesh geometry={nodes['������������_������_1_1_����������������7_13_2'].geometry} material={materials['.7_1']} />
          <mesh geometry={nodes['������������_������_1_1_����������������15_13_1'].geometry} material={materials['.15_0']} />
          <mesh geometry={nodes['������������_������_1_1_����������������3_13_1'].geometry} material={materials['.3_1']} />
          <mesh geometry={nodes['������������_������_1_1_����������������1_13_2'].geometry} material={materials['.1_2']} />
          <mesh geometry={nodes['������������_������_1_1_����������������8_13_2'].geometry} material={materials['.8_1']} />
          <mesh geometry={nodes['������������_������_1_1_����������������14_13_2'].geometry} material={materials['.14_1']} />
          <mesh geometry={nodes['������������_������_1_1_����������������2_13_1'].geometry} material={materials['.2_1']} />
          <mesh geometry={nodes['������������_������_1_1_����������������_4'].geometry} material={materials.material_14} />
          <mesh geometry={nodes['������������_������_1_1_����������������1_13_3'].geometry} material={materials['.1_3']} />
          <mesh geometry={nodes['������������_������_1_1_����������������1_0'].geometry} material={materials['.1_3']} />
          <mesh geometry={nodes['������������_������_1_1_����������������_13'].geometry} material={materials.material} />
          <mesh geometry={nodes['������������_������_1_1_����������������_13_1'].geometry} material={materials.material_10} />
          <mesh geometry={nodes['������������_������_1_1_����������������2_3'].geometry} material={materials['.2_2']} />
        </group>
        <group position={[-6382.163, 5991.59, 597.05]} rotation={[0, -1.302, 0]}>
          <mesh geometry={nodes['������������_������_1_����������������_0'].geometry} material={materials.material_72} />
          <mesh geometry={nodes['������������_������_1_����������������2_0'].geometry} material={materials['.2_3']} />
          <mesh geometry={nodes['������������_������_1_����������������1_0'].geometry} material={materials['.1_4']} />
          <mesh geometry={nodes['������������_������_1__0'].geometry} material={materials['1_1__13']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/low_poly_city_pack.glb')
